options:
  aci-repo:
    type: string
    default: 'deb http://a.b.c.d'
    description: "Apt repository for ACI module"
  aci-repo-key:
    type: string
    default:
    description: "Repo key, if missing no package authentication will be performed"
  aci-apic-hosts:
    type: string
    default: 1.1.1.1
    description: "comma separated string of apic hostnames or ip addresses"
  aci-apic-username:
    type: string
    default: admin
    description: "APIC username"
  aci-apic-password:
    type: string
    default:
    description: "APIC password"
  aci-apic-system-id:
    type: string
    default: 'openstack'
    description: "As id string for this openstack instance"
  aci-apic-entity-profile:
    type: string
    default:
    description: "ACI Attached Entity Profile that is configured on fabric, where the nodes are connected"
  aci-encap:
    type: string
    default: vxlan
    description: "vlan or vxlan"
  aci-vlan-ranges:
    type: string
    default: 1000:1010
    description: "Vlan range to use when aci_encap for vmm domain in of type vlan"
  aci-connection-json:
    type: string
    default:
    description: "Describe nova-compute connections to ACI leaf in JSON format. Example {'101': ['host1.domain:1/1', 'host2.domain:1/2'], '102':['host3.domain:1/4']}. 101 is the switch id, host1.domain is connected to port 1/1 "
  aci-vpc-pairs:
    type: string
    default:
    description: "If using VPC to connect the nodes to ACI leaf switches, specify the switch id pairs for vpc. Example, if switch ids 101 and 102 form a vpc pair and switch ids 103, 104 form a vpc pair, then set the value to '101:102,103:104'"
  aci-enable-optimized-metadata:
    type: boolean
    default: True
    description: "enable optimized metadata"
  rabbit-user:
    default: neutron
    type: string
    description: Username used to access RabbitMQ queue
  rabbit-vhost:
    default: openstack
    type: string
    description: RabbitMQ vhost
  database-user:
    default: neutron
    type: string
    description: Username for Neutron database access (if enabled)
  database:
    default: neutron
    type: string
    description: Database name for Neutron (if enabled)
